version: "3.7"
services:
  db:
    image: mongo:3.4

  tests:
    build: .
    depends_on:
      - db
    environment:
      MONGO_HOST: db
    entrypoint: bundle exec rspec spec

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      MONGO_HOST: db
      SECRET: "himitsu"
      ELIXIR_MS_HOSTNAME: jep-capture_app_1
    command: /bin/sh -c "rm -f /rails/tmp/pids/server.pid"
    entrypoint: bin/server

  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      MONGO_HOST: db
      SECRET: "himitsu"
      ELIXIR_MS_HOSTNAME: jep-capture_app_1
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: bash -c "bin/setup-dev && bundle exec rails s -b 0.0.0.0"
