version: "3.7"
services:
  db:
    image: mongo:3.4

  tests:
    build: .
    depends_on:
      - db
    environment:
      MONGO_HOST: db
    entrypoint: bundle exec rspec spec

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      MONGO_HOST: db
      SECRET: "himitsu"
    command: /bin/sh -c "rm -f /rails/tmp/pids/server.pid"
    entrypoint: bin/server